// File: src/utils/mockCategories.ts

// Define the Category interface
export interface Category {
    id: number;
  image: string;
  name: string;
  price: number;
  description: string;
  category: string;
  badge?: string; // Badge like "New" or "Sale"
  originalPrice?: number; // Original price if the product is on sale
  nameStyle?: string; // Custom styles for product name
  priceStyle?: string; // Custom styles for price
  cartColor?: string; // Tailwind color classes for cart button
  iconColor?: string; // Tailwind color classes for cart icon

  }
  
  // Mock category data
  export const mockCategories: Category[] = [
    {
      id: 4001,
      image: "/assets/images/white-chair.png",
      name: "Library Stool Chair",
      price: 59.99,
      description: "Comfortable and stylish chair for your library.",
      category: "chairs",
      badge: "New",
      nameStyle: "text-lg font-[400] text-[#007580]",
      priceStyle: "text-[#000000] font-[400]",
      cartColor: "bg-[#029fae]",
      iconColor: "text-white",
  },
  {
      id: 4002,
      image: "/assets/images/pink-chair.png",
      name: "Modern Pink Chair",
      price: 89.99,
      originalPrice: 119.99,
      description: "Elegant pink chair for a modern touch in any room.",
      category: "chairs",
      badge: "Sale",
      nameStyle: "text-lg font-medium",
      priceStyle: "text-black font-medium",
      cartColor: "bg-[#f0f2f3]",
      iconColor: "text-black",
  },
  {
      id: 4003,
      image: "/assets/images/orange-chair.png",
      name: "Ergonomic Orange Chair",
      price: 129.99,
      description: "Bright and ergonomic chair for your workspace.",
      category: "chairs",
      nameStyle: "text-lg font-[400] text-[#000000]",
      priceStyle: "text-[#000000] font-[400]",
      cartColor: "bg-[#f0f2f3]",
      iconColor: "text-black",
  },
  {
      id: 4004,
      image: "/assets/images/white-rounded-chair.png",
      name: "Rounded White Chair",
      price: 149.99,
      description: "Elegant rounded chair, perfect for any setting.",
      category: "chairs",
      nameStyle: "text-lg font-[400] text-[#000000]",
      priceStyle: "text-[#000000] font-[400]",
      cartColor: "bg-[#f0f2f3]",
      iconColor: "text-black",
  },
  {
      id: 4005,
      image: "/assets/images/wooden-chair.png",
      name: "Classic Wooden Chair",
      price: 79.99,
      description: "Stylish wooden chair with a vintage feel.",
      category: "chairs",
      badge: "New",
      nameStyle: "text-lg font-medium",
      priceStyle: "text-black font-medium",
      cartColor: "bg-[#f0f2f3]",
      iconColor: "text-black",
  },
  {
    id: 4006,
    image: "/assets/images/computer-chair.png",
    name: "Modern Computer Chair",
    price: 129.99,
    originalPrice: 179.99,
    description: "Comfortable computer chair for long hours of work.",
    category: "chairs",
    badge: "Sale",
    nameStyle: "text-lg font-medium",
    priceStyle: "text-black font-medium",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
},
{
    id: 4007,
    image: "/assets/images/chair-cushion.png",
    name: "Cushioned Chair",
    price: 99.99,
    description: "Cozy chair with a plush cushion for extra comfort.",
    category: "chairs",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
},
{
    id: 4008,
    image: "/assets/images/white-chair.png",
    name: "Minimalist White Chair",
    price: 89.99,
    description: "Simple and minimalist white chair for modern spaces.",
    category: "chairs",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
},
{
    id: 4009,
    image: "/assets/images/computer-chair.png",
    name: "Executive Chair",
    price: 189.99,
    description: "Modern executive chair for a professional workspace.",
    category: "chairs",
    badge: "New",
    nameStyle: "text-lg font-[400] text-[#007580]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#029fae]",
    iconColor: "text-white",
},
{
    id: 4010,
    image: "/assets/images/pink-chair.png",
    name: "Pink Library Chair",
    price: 119.99,
    originalPrice: 159.99,
    description: "Vibrant pink chair for an elegant library look.",
    category: "chairs",
    badge: "Sale",
    nameStyle: "text-lg font-medium",
    priceStyle: "text-black font-medium",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
},
{
    id: 4011,
    image: "/assets/images/orange-chair.png",
    name: "Bright Orange Chair",
    price: 109.99,
    description: "Eye-catching orange chair for bold interiors.",
    category: "chairs",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
},
{
    id: 4012,
    image: "/assets/images/stand-chair.png",
    name: "Standing Chair",
    price: 129.99,
    description: "Versatile standing chair for ergonomic use.",
    category: "chairs",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
},
{
    id: 4013,
    image: "/assets/images/cozy-sofa.png",
    name: "Cozy Sofa",
    price: 399.99,
    description: "A comfortable and stylish sofa for relaxation.",
    category: "sofas",
    badge: "New",
    nameStyle: "text-lg font-[400] text-[#007580]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#029fae]",
    iconColor: "text-white",
},
{
    id: 4014,
    image: "/assets/images/galaxy-sofa.png",
    name: "Galaxy Sofa",
    price: 499.99,
    description: "A luxurious sofa with a modern touch.",
    category: "sofas",
    badge: "New",
    nameStyle: "text-lg font-[400] text-[#007580]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#029fae]",
    iconColor: "text-white",
},
{
    id: 4015,
    image: "/assets/images/greylistic-sofa.png",
    name: "Grey Lounge Sofa",
    price: 429.99,
    description: "Minimalist grey sofa for modern spaces.",
    category: "sofas",
    badge: "New",
    nameStyle: "text-lg font-[400] text-[#007580]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#029fae]",
    iconColor: "text-white",
},

{
  id: 4016,
  image: "/assets/images/white-elegant-seater-sofa.png",
  name: "White Elegant Sofa",
  price: 599.99,
  description: "Elegant white sofa for stylish interiors.",
  category: "sofas",
  badge: "New",
  nameStyle: "text-lg font-[400] text-[#007580]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#029fae]",
  iconColor: "text-white",
},
{
  id: 4017,
  image: "/assets/images/luxury-sofa.png",
  name: "Luxury Lounge Sofa",
  price: 799.99,
  description: "A premium sofa designed for maximum comfort.",
  category: "sofas",
  badge: "New",
  nameStyle: "text-lg font-[400] text-[#007580]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#029fae]",
  iconColor: "text-white",
},
{
  id: 4018,
  image: "/assets/images/mint-green-sofa.png",
  name: "Mint Green Sofa",
  price: 529.99,
  description: "Aesthetic mint green sofa for a refreshing look.",
  category: "sofas",
  badge: "New",
  nameStyle: "text-lg font-[400] text-[#007580]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#029fae]",
  iconColor: "text-white",
},
{
  id: 4019,
  image: "/assets/images/modern-sofa.png",
  name: "Modern Grey Sofa",
  price: 649.99,
  description: "A sleek and modern sofa with a contemporary design.",
  category: "sofas",
  badge: "New",
  nameStyle: "text-lg font-[400] text-[#007580]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#029fae]",
  iconColor: "text-white",
},
{
  id: 4020,
  image: "/assets/images/cushion-sofa.png",
  name: "Cushioned Sofa",
  price: 689.99,
  description: "A plush cushioned sofa designed for ultimate relaxation.",
  category: "sofas",
  badge: "New",
  nameStyle: "text-lg font-[400] text-[#007580]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#029fae]",
  iconColor: "text-white",
},
{
  id: 4021,
  image: "/assets/images/plank-table.png",
  name: "Rustic Plank Table",
  price: 299.99,
  description: "A solid wooden table with a rustic and elegant design.",
  category: "tables",
  badge: "New",
  nameStyle: "text-lg font-[400] text-[#007580]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#029fae]",
  iconColor: "text-white",
},
{
  id: 4022,
  image: "/assets/images/office-front-table.png",
  name: "Minimalist Front Table",
  price: 199.99,
  originalPrice: 259.99,
  description: "A sleek and modern front table for stylish interiors.",
  category: "tables",
  badge: "Sale",
  nameStyle: "text-lg font-medium",
  priceStyle: "text-black font-medium",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},
{
  id: 4023,
  image: "/assets/images/century-table.png",
  name: "Century Wooden Table",
  price: 349.99,
  description: "A classic wooden table with a century-inspired design.",
  category: "tables",
  nameStyle: "text-lg font-[400] text-[#000000]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},
{
  id: 4024,
  image: "/assets/images/graham-study- table.png",
  name: "Graham Study Table",
  price: 259.99,
  description: "A study table with ample space for books and accessories.",
  category: "tables",
  nameStyle: "text-lg font-[400] text-[#000000]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},

{
  id: 4025,
  image: "/assets/images/fasso-dinning-table.png",
  name: "Fasso Dining Table",
  price: 399.99,
  description: "A stylish dining table with a timeless wooden finish.",
  category: "tables",
  badge: "New",
  nameStyle: "text-lg font-medium",
  priceStyle: "text-black font-medium",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},
{
  id: 4026,
  image: "/assets/images/boom-coffee-table.png",
  name: "Boom College Desk",
  price: 189.99,
  originalPrice: 249.99,
  description: "A practical and modern college desk for students.",
  category: "tables",
  badge: "Sale",
  nameStyle: "text-lg font-medium",
  priceStyle: "text-black font-medium",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},
{
  id: 4027,
  image: "/assets/images/royal-bed.png",
  name: "Royal Bed",
  price: 999.99,
  description: "A luxurious royal bed designed for ultimate comfort.",
  category: "beds",
  badge: "New",
  nameStyle: "text-lg font-[400] text-[#007580]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#029fae]",
  iconColor: "text-white",
},
{
  id: 4028,
  image: "/assets/images/couple-bed.png",
  name: "Couple Bed",
  price: 799.99,
  originalPrice: 999.99,
  description: "A spacious and stylish bed perfect for couples.",
  category: "beds",
  badge: "Sale",
  nameStyle: "text-lg font-medium",
  priceStyle: "text-black font-medium",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},
{
  id: 4029,
  image: "/assets/images/lunetto-bed.png",
  name: "Lunetto Bed",
  price: 729.99,
  description: "A modern Lunetto-style bed for contemporary interiors.",
  category: "beds",
  nameStyle: "text-lg font-[400] text-[#000000]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},
{
  id: 4030,
  image: "/assets/images/modern-bed.png",
  name: "Modern Bed",
  price: 849.99,
  description: "Minimalist modern bed with a sleek finish.",
  category: "beds",
  nameStyle: "text-lg font-[400] text-[#000000]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},
{
  id: 4031,
  image: "/assets/images/solid-wood-storage.png",
  name: "Solid Wood Storage",
  price: 349.99,
  description: "A durable and elegant solid wood storage unit.",
  category: "storages",
  nameStyle: "text-lg font-[400] text-[#000000]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},
{
  id: 4032,
  image: "/assets/images/drop-front-storage.png",
  name: "Drop Front Storage Cabinet",
  price: 279.99,
  description: "A stylish drop-front storage cabinet for organization.",
  category: "storages",
  nameStyle: "text-lg font-[400] text-[#000000]",
  priceStyle: "text-[#000000] font-[400]",
  cartColor: "bg-[#f0f2f3]",
  iconColor: "text-black",
},

];

  
  // Simulate delay for async operations
const simulateDelay = <T>(data: T, delay = 500): Promise<T> =>
  new Promise((resolve) => setTimeout(() => resolve(data), delay));

// Fetch all categories
export const fetchAllCategories = async (): Promise<Category[]> => {
  return simulateDelay(mockCategories);
};

// Fetch category by ID
export const fetchCategoryById = async (id: number): Promise<Category> => {
  const category = mockCategories.find((category) => category.id === id);
  if (!category) throw new Error(`Category with ID ${id} not found.`);
  return simulateDelay(category);
};

// Fetch related categories by name
export const fetchRelatedCategories = async (name: string): Promise<Category[]> => {
  const relatedCategories = mockCategories.filter(
      (category) => category.name.toLowerCase().includes(name.toLowerCase())
  );
  if (relatedCategories.length === 0) {
      throw new Error(`No categories found for: ${name}`);
  }
  return simulateDelay(relatedCategories);
};
