// File: src/utils/mockProducts.ts

// Define the Product interface
export interface Product {
  id: number;
  image: string;
  name: string;
  price: number;
  description: string;
  category: string;
  badge?: string; // Optional instead of `null`
  originalPrice?: number; // Optional
  nameStyle?: string;
  priceStyle?: string;
  cartColor?: string;
  iconColor?: string;
}

// Mock product data
export const mockProducts: Product[] = [
  {
    id: 3001,
    image: "/assets/images/white-chair.png",
    name: "Library Stool Chair",
    price: 59.99,
    description: "Comfortable and stylish chair for your library.",
    category: "chairs",
    badge: "New",
    nameStyle: "text-lg font-[400] text-[#007580]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#029fae]",
    iconColor: "text-white",
  },
  {
    id: 3002,
    image: "/assets/images/pink-chair.png",
    name: "Modern Pink Chair",
    price: 89.99,
    originalPrice: 30.0,
    description: "Elegant pink chair for a modern touch in any room.",
    category: "chairs",
    badge: "Sale",
    nameStyle: "text-lg font-medium",
    priceStyle: "text-black font-medium",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id: 3003,
    image: "/assets/images/orange-chair.png",
    name: "Ergonomic Orange Chair",
    price: 129.99,
    description: "Bright and ergonomic chair for your workspace.",
    category: "furniture",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id: 3004,
    image: "/assets/images/white-rounded-chair.png",
    name: "Rounded White Chair",
    price: 149.99,
    description: "Elegant rounded chair, perfect for any setting.",
    category: "chairs",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id: 3005,
    image: "/assets/images/wooden-chair.png",
    name: "Classic Wooden Chair",
    price: 79.99,
    description: "Stylish wooden chair with a vintage feel.",
    category: "chairs",
    badge: "New",
    nameStyle: "text-lg font-medium",
    priceStyle: "text-black font-medium",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id: 3006,
    image: "/assets/images/computer-chair.png",
    name: "Modern Computer Chair",
    price: 129.99,
    originalPrice: 179.99,
    description: "Comfortable computer chair for long hours of work.",
    category: "chairs",
    badge: "Sale",
    nameStyle: "text-lg font-medium",
    priceStyle: "text-black font-medium",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id: 3007,
    image: "/assets/images/chair-cushion.png",
    name: "Cushioned Chair",
    price: 99.99,
    description: "Cozy chair with a plush cushion for extra comfort.",
    category: "furniture",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id: 3008,
    image: "/assets/images/white-chair.png",
    name: "Minimalist White Chair",
    price: 89.99,
    description: "Simple and minimalist white chair for modern spaces.",
    category: "chairs",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id: 3009,
    image: "/assets/images/computer-chair.png",
    name: "Executive Chair",
    price: 189.99,
    description: "Modern executive chair for a professional workspace.",
    category: "chairs",
    badge: "New",
    nameStyle: "text-lg font-[400] text-[#007580]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#029fae]",
    iconColor: "text-white",
  },
  {
    id: 3010,
    image: "/assets/images/pink-chair.png",
    name: "Pink Library Chair",
    price: 119.99,
    originalPrice: 159.99,
    description: "Vibrant pink chair for an elegant library look.",
    category: "chairs",
    badge: "Sale",
    nameStyle: "text-lg font-medium",
    priceStyle: "text-black font-medium",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id: 3011,
    image: "/assets/images/orange-chair.png",
    name: "Bright Orange Chair",
    price: 109.99,
    description: "Eye-catching orange chair for bold interiors.",
    category: "chairs",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
    id:3012,
    image: "/assets/images/stand-chair.png",
    name: "Standing Chair",
    price: 129.99,
    description: "Versatile standing chair for ergonomic use.",
    category: "chairs",
    nameStyle: "text-lg font-[400] text-[#000000]",
    priceStyle: "text-[#000000] font-[400]",
    cartColor: "bg-[#f0f2f3]",
    iconColor: "text-black",
  },
  {
id: 3013,
image: "/assets/images/cozy-sofa.png",
name: "Cozy Sofa",
price: 399.99,
description: "A comfortable and stylish sofa for relaxation.",
category: "sofas",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3014,
image: "/assets/images/galaxy-sofa.png",
name: "Galaxy Sofa",
price: 499.99,
description: "A luxurious sofa with a modern touch.",
category: "furniture",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3015,
image: "/assets/images/greylistic-sofa.png",
name: "Grey Lounge Sofa",
price: 429.99,
description: "Minimalist grey sofa for modern spaces.",
category: "sofas",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3016,
image: "/assets/images/white-elegant-seater-sofa.png",
name: "White Elegant Sofa",
price: 599.99,
description: "Elegant white sofa for stylish interiors.",
category: "sofas",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3017,
image: "/assets/images/luxury-sofa.png",
name: "Luxury Lounge Sofa",
price: 799.99,
description: "A premium sofa designed for maximum comfort.",
category: "sofas",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3018,
image: "/assets/images/mint-green-sofa.png",
name: "Mint Green Sofa",
price: 529.99,
description: "Aesthetic mint green sofa for a refreshing look.",
category: "sofas",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3019,
image: "/assets/images/modern-sofa.png",
name: "Modern Grey Sofa",
price: 649.99,
description: "A sleek and modern sofa with a contemporary design.",
category: "sofas",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3020,
image: "/assets/images/cushion-sofa.png",
name: "Cushioned Sofa",
price: 689.99,
description: "A plush cushioned sofa designed for ultimate relaxation.",
category: "sofas",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3021,
image: "/assets/images/plank-table.png",
name: "Rustic Plank Table",
price: 299.99,
description: "A solid wooden table with a rustic and elegant design.",
category: "tables",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3022,
image: "/assets/images/office-front-table.png",
name: "Minimalist Front Table",
price: 199.99,
originalPrice: 259.99,
description: "A sleek and modern front table for stylish interiors.",
category: "tables",
badge: "Sale",
nameStyle: "text-lg font-medium",
priceStyle: "text-black font-medium",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3023,
image: "/assets/images/century-table.png",
name: "Century Wooden Table",
price: 349.99,
description: "A classic wooden table with a century-inspired design.",
category: "tables",
nameStyle: "text-lg font-[400] text-[#000000]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3024,
image: "/assets/images/graham-study- table.png",
name: "Graham Study Table",
price: 259.99,
description: "A study table with ample space for books and accessories.",
category: "tables",
nameStyle: "text-lg font-[400] text-[#000000]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3025,
image: "/assets/images/fasso-dinning-table.png",
name: "Fasso Dining Table",
price: 399.99,
description: "A stylish dining table with a timeless wooden finish.",
category: "tables",
badge: "New",
nameStyle: "text-lg font-medium",
priceStyle: "text-black font-medium",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3026,
image: "/assets/images/boom-coffee-table.png",
name: "Boom College Desk",
price: 189.99,
originalPrice: 249.99,
description: "A practical and modern college desk for students.",
category: "tables",
badge: "Sale",
nameStyle: "text-lg font-medium",
priceStyle: "text-black font-medium",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3027,
image: "/assets/images/royal-bed.png",
name: "Royal Bed",
price: 999.99,
description: "A luxurious royal bed designed for ultimate comfort.",
category: "tables",
badge: "New",
nameStyle: "text-lg font-[400] text-[#007580]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#029fae]",
iconColor: "text-white",
},
{
id: 3028,
image: "/assets/images/couple-bed.png",
name: "Couple Bed",
price: 799.99,
originalPrice: 999.99,
description: "A spacious and stylish bed perfect for couples.",
category: "beds",
badge: "Sale",
nameStyle: "text-lg font-medium",
priceStyle: "text-black font-medium",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3029,
image: "/assets/images/lunetto-bed.png",
name: "Lunetto Bed",
price: 729.99,
description: "A modern Lunetto-style bed for contemporary interiors.",
category: "furnitur",
nameStyle: "text-lg font-[400] text-[#000000]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3030,
image: "/assets/images/modern-bed.png",
name: "Modern Bed",
price: 849.99,
description: "Minimalist modern bed with a sleek finish.",
category: "beds",
nameStyle: "text-lg font-[400] text-[#000000]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3031,
image: "/assets/images/solid-wood-storage.png",
name: "Solid Wood Storage",
price: 349.99,
description: "A durable and elegant solid wood storage unit.",
category: "storages",
nameStyle: "text-lg font-[400] text-[#000000]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
{
id: 3032,
image: "/assets/images/drop-front-storage.png",
name: "Drop Front Storage Cabinet",
price: 279.99,
description: "A stylish drop-front storage cabinet for organization.",
category: "storages",
nameStyle: "text-lg font-[400] text-[#000000]",
priceStyle: "text-[#000000] font-[400]",
cartColor: "bg-[#f0f2f3]",
iconColor: "text-black",
},
];

// Simulate delay for async operations
const simulateDelay = <T>(data: T, delay = 500): Promise<T> =>
  new Promise((resolve) => setTimeout(() => resolve(data), delay));

// Fetch all products
export const fetchAllProducts = async (): Promise<Product[]> => {
  return simulateDelay(mockProducts);
};

// Fetch product by ID
export const fetchProductById = async (id: number): Promise<Product> => {
  const product = mockProducts.find((product) => product.id === id);
  if (!product) throw new Error(`Product with ID ${id} not found.`);
  return simulateDelay(product);
};

// Fetch related products by category
export const fetchRelatedProducts = async (category: string): Promise<Product[]> => {
  const relatedProducts = mockProducts.filter(
    (product) => product.category === category
  );
  if (relatedProducts.length === 0) {
    throw new Error(`No products found in category: ${category}`);
  }
  return simulateDelay(relatedProducts);
};
